Michael turner exercises - ex01_basics: WordCounter
mantidproject/newstarter pull request #25
Opened 2017-07-05 15:01 UTC by michaeljturner

Have written the WordCounter program for ex01_basics.  Runs correctly and outputs data in a file, in the same directory as the input file.

2017-07-07 12:10 UTC, gemmaguest submitted a review, later dismissed
Very nice code :+1: :+1:. I've made lots of comments but they're mainly style points & tips. See in-line comments.

2017-07-07 12:10 UTC, gemmaguest commented on exercises/michael_turner/ex01_basics/src/counter.cpp
> +	while (  i != line.size()){
While this is logically fine, it's generally better to use less-than rather than not-equal when iterating through indices like this, i.e. `while (i < line.size())`. It aids clarity about what the intent is and avoids any potential mishaps if somehow `i` ends up > `line.size`.

2017-07-07 12:10 UTC, gemmaguest commented on exercises/michael_turner/ex01_basics/src/counter.cpp
> +
Would it be worth adding an early `break` here if `i >= line.size()`?

2017-07-07 12:10 UTC, gemmaguest commented on exercises/michael_turner/ex01_basics/src/counter.cpp
> +		++k;
Since `k` is not used in many places you could just use `j+1`, and this might actually aid clarity (see below about indexing out of range). I'm ambivalent on this, though.

2017-07-07 12:10 UTC, gemmaguest commented on exercises/michael_turner/ex01_basics/src/counter.cpp
> +		while ( j != line.size() && !isPunc(line[j]) && !(isHyphen(line[j]) && isHyphen(line[k]) )){
Is it possible that `line[k]` could be out of range here? This is where I think using `j+1` instead might add clarity.

Also, this is another place I'd use `j < line.size`

2017-07-07 12:10 UTC, gemmaguest commented on exercises/michael_turner/ex01_basics/src/counter.cpp
> +		while (i != line.size() && (isPunc(line[i]) || isHyphen(line[i])) )
Again, I'd use `i < line.size()` here

2017-07-07 12:10 UTC, gemmaguest commented on exercises/michael_turner/ex01_basics/src/counter.cpp
> + *		@param line	The input text containing words to be counted
As I mentioned, you have tabs instead of spaces. This will be fixed by clang-format in the main repository, but it's good to set up your editor to use spaces instead of tabs or you'll constantly get annoying clang-format errors.

2017-07-07 12:10 UTC, gemmaguest commented on exercises/michael_turner/ex01_basics/src/counter.cpp
> +	for (wordRank::const_reverse_iterator it = rank.rbegin(); it != rank.rend(); ++it)
This is a good place to use `auto` to aid readability: `auto it = rank.rbegin()`

2017-07-07 12:10 UTC, gemmaguest commented on exercises/michael_turner/ex01_basics/src/counter.cpp
> +		outFile << std::left << std::setw(OUT_WIDTH) << it -> second << it -> first << std::endl;
Just a minor formatting comment, but these lines will both end up being split over 2 lines by clang-format. I generally wrap the contents of `for`, `if` etc. in braces unless it's a very short one-liner. This is more of a personal preference (probably a hangover from a previous job where braces were always mandatory!), but I have seen cases where the intent was lost because braces weren't used.

Also, clang-format will remove the spaces in e.g. `it -> second`

2017-07-07 12:10 UTC, gemmaguest commented on exercises/michael_turner/ex01_basics/src/counter.h
> +const int OUT_WIDTH = 20;
It's best to keep these out of the header file unless they're intended to be used elsewhere - I think they're only used in `counter.cpp` so they could go in there? It's also good to be explicit that they should use internal linkage by specifying them as `static const`, or putting them in an unnamed namespace (I think the latter is preferred). Alternatively, if they're only used in one function they could be `static const` inside that function.

2017-07-07 12:10 UTC, gemmaguest commented on exercises/michael_turner/ex01_basics/src/counter.h
> +
Again, I think `wordRank` and `string_size` could be moved to `counter.cpp`

2017-07-07 12:10 UTC, gemmaguest commented on exercises/michael_turner/ex01_basics/src/counter.h
> +
Again, I think declarations for `flipMap`, `isPunc` and `isHyphen` don't need to be in the header if they're only used in `counter.cpp` - in which case they should also be declared `static` or put in an anonymous namespace so they have internal linkage.

2017-07-07 12:10 UTC, gemmaguest commented on exercises/michael_turner/ex01_basics/src/counter.h
> +//Stores individual words and increments an associated counter
I think the comments for the functions should have triple slash `///` so they get documented in doxygen.

2017-07-07 12:10 UTC, gemmaguest commented on exercises/michael_turner/ex01_basics/src/main.cpp
> +				rankWords(counters, outFile);
Very minor point, but it wasn't immediately clear to me that this is where the output file is written, so perhaps a comment or more descriptive name for this function would help.

2017-07-07 12:13 UTC, gemmaguest commented on exercises/michael_turner/ex01_basics/src/counter.h
> +
Also, the naming convention for typedefs is PascalCase, e.g. `WordMap` instead of `wordMap`

2017-07-10 09:16 UTC, michaeljturner commented on exercises/michael_turner/ex01_basics/src/counter.h
> +//Stores individual words and increments an associated counter
I think you can use either /**, /*! or /// (on every line)

2017-07-12 12:28 UTC, gemmaguest requested changes
Exercise 2 looks good :+1: :+1:. I've added a few suggestions for improvements, mainly relating to style and good practice. I've also noted some alternative ways things could be implemented, although these are more for info as they're not particularly relevant to this example.

2017-07-12 12:28 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shape_sorter.cpp
> +ShapeSorter::ShapeSorter(std::vector<std::reference_wrapper<Shape> > &v): shapes(v){}
You could add a typedef for `std::vector<std::reference_wrapper<Shape> >`. This is used in quite a lot of places so if it was replaced with, say, `ShapeVector` it would make the code more readable.

2017-07-12 12:28 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shape_sorter.cpp
> +    for(std::multimap<double, std::reference_wrapper<Shape>>::const_reverse_iterator iter = rank.rbegin(); iter != rank.rend(); ++iter){
You could use `auto` here to make it more readable. It's also good to use `crbegin` and `crend` (or `cbegin` and `cend` for forward iterators) if you want a const iterator.

2017-07-12 12:28 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shape_sorter.cpp
> +    for(auto iter = sorted.begin(); iter < sorted.end(); ++iter){
You can use a range-based for loop for better readability here and in other for loops:
```
for (const auto &shape_ref : sorted) {
  shape_ref.get().printShape();
}
```
Note that this gives you the actual values from the vector rather than iterators, so it's good practice to use `const auto &` to take a reference, otherwise you can end up with unnecessary copies.

2017-07-12 12:28 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shapes.h
> +
In Mantid we'd have a separate header for each class, but don't worry for this small example

2017-07-12 12:28 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shapes.h
> +    ///Virtual destructor
The virtual destructor is commented but not declared! Did you mean to add add it here? It's important to have a virtual destructor in the base class, even if you just want the default destructor - a neat way to make the default destructor virtual is `virtual ~Shape() = default;`

2017-07-12 12:28 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shapes.h
> +    virtual double getArea() const {return 0;}
I think it's worth making the virtual functions pure virtual because they are required in all of the derived classes. This will make the base class an abstract class, which I think makes sense because you probably wouldn't want to create a `Shape` without knowing what type of shape it was.

2017-07-12 12:28 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shape_sorter.cpp
> +        if (!(iter->get().getType().compare(type))){
If efficiency was a concern it would be better to make the type an enum to avoid needing to do string comparisons to check the type. Your solution is fine for this example though and has the benefit that it avoids the need to convert the enum to a string for the output.

2017-07-12 12:28 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shapes.cpp
> +    }
Storing the attributes like this means you have a nice simple way to print them all in a consistent format :+1:. Just for info, a common approach is to have a virtual function to print the object, where each derived class takes care of printing itself. This is common in more complex classes where it's beneficial to have direct access to the class members to do the printing.

2017-07-12 12:28 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shapes.h
> +    double getArea() const;
It's good practice to add the `override` keyword when you override a function in a derived class, e.g. `double getArea() const override;`. It's functionally the same but makes the intent clear, and the compiler can do some extra checks.

2017-07-12 12:28 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shapes.h
> +    std::string getType() const;
`getType` and `getSides` could be made pure virtual functions, where the overrides in the derived classes directly return the hard-coded values. This would mean that you don't need to store their values in the base class, and the `CIRCLE_NAME`, `CIRCLE_SIDES` etc. definitions in the anonymous namespace would not be needed. See the note on the `type` member below.

2017-07-12 12:28 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shapes.cpp
> +}
While an anonymous namespace is a good place to put these, since they are specific to particular classes they could be encapsulated further by putting this info into those classes. See the comment below on overriding the `getType` and `getSides` functions. `PI` could be made a static private member of `Circle`, and using constexpr means you can initialise it within the class definition i.e. `static constexpr double PI = 3.14159;`

2017-07-12 12:28 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shapes.h
> +    std::map<std::string, double> dimensions;
If you make `dimensions` `protected` instead of `private`, then it can be edited directly from the derived classes, and you can get rid of the `setDim` function. There might be situations where you'd want a base class function to do this instead, e.g. to do some common processing after setting the variable, but in this case I think it's unnecessary.

2017-07-12 12:28 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shapes.cpp
> +}
As noted in the `Shape` class, if you make `dimensions` `protected` then it can be used directly here instead of creating the temporary `dim` object, and `setDim` could be removed. Likewise for the other derived classes.

2017-07-12 12:28 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shapes.cpp
> +}
As noted in the `Shape` class, `getType` could be made virtual and return the hard-coded value directly from the derived function overrides, rather than it having to be stored in the `type` member variable.

2017-07-12 12:28 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shapes.h
> +    std::string type;
As noted above, `type` and `numSides` wouldn't need to be stored if they were returned by overrides of `getType` and `getSides`. This would save a bit of memory (only a concern if there are likely to be many instances of these classes), and avoids any possibility that these values could be changed accidentally at runtime. However, polymorphism can add a performance overhead so if that were an issue then your implementation would be better. None of these issues is important for this example so I'm ambivalent if you want to make this change or not :)

2017-07-14 10:17 UTC, michaeljturner commented
Have updated ShapeSorter exercise

2017-07-14 10:48 UTC, gemmaguest approved these changes
The changes look good :+1: Happy for this to go to the gatekeeper @AntonPiccardoSelg

2017-07-14 10:48 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shape_sorter.cpp
> +    for(const auto &shape_ref: sorted){
Doh, I think I suggested the name `shape_ref` (old habit) but actually the convention in Mantid is for camelCase variable names. My bad. No need to change it.

2017-07-14 10:48 UTC, gemmaguest commented on exercises/michael_turner/ex02_oo_basics/src/shape_sorter.cpp
> +        rank.insert(std::pair<double, std::reference_wrapper<Shape>>(shape_ref.get().getArea(), shape_ref.get()));
No need to change it, but you could use `std::make_pair` here to improve readability (it avoids having to specify the element types).

2017-08-09 12:17 UTC, gemmaguest commented
I think we forgot to close this PR.

2017-08-09 12:17 UTC, closed without merging