New-starter exercises
mantidproject/newstarter pull request #77
Opened 2021-02-10 17:28 UTC by srikanthravipati

2021-02-15 16:05 UTC, Pasarus requested changes
This is for Exercise 1:
I am curious as to why you separated the processLine.cpp/.h files out? would it have made more sense to leave it in the main.cpp/.h files, considering it's such a small program.

With the function of ex01, it seems outfile.txt is correct but poorly formatted, would be better if the tabulation was better e.g. 
![image](https://user-images.githubusercontent.com/24723609/107927268-aaf1ef80-6f6e-11eb-998f-90f883ad30d7.png)

Largely so far everything I have seen has been good code, just some formatting bits, in Mantid we try to follow this set of coding guidelines https://developer.mantidproject.org/Standards/CPPStandards.html, which are loosely just based on LLVM (https://llvm.org/docs/CodingStandards.html) and thus enforced by clang-format, at least in the main repository. I'll try to make any changes a Github PR suggestion so easy to add to your PR. It seems like on the whole you just lack whitespace in certain places.

Could I suggest using an auto-formatter (Clang-format) on your IDE/text editor of choice? I realize this isn't always possible but we have examples for VSCode.

I really like your use of the Standard Template Library, it's always refreshing to see new solutions using them.

In Summary:
- Use more whitespace between types in definitions/declarations
- Use range-based for-loops where possible
- Ensure consistent use of whitespace
- Use an auto-formatter to sort most of the formatting issues for you. This will stop the back and forth between you and the build servers in the main repo.

To finish this PR for exercise 1, apply any formatting suggestions in exercise 1,sort the formatting of the output file so that tabulation lines up in the file, enforce use of st d:: namespace, and replace for_each with range based for loops.

Exercise 2:
With exercise 2 it looks good, I have made a suggestion for each file where the formatting would be better in line with how we run it in the main mantid repo. Please don't be discouraged by these they are actually meant to just be a way for you to easily see the differences in usual programming format. Funnily enough, you used much more white space in this exercise and it doesn't look bad, it's just not our current standard.

The exercise explicitly asks for a Square shape, I like that you handled it using the Rectangle, it is a nice solution.

Split out the shapes into the different header files, enforce std:: name spacing on sort, and replace for each with a range-based for loop and this code should be good to go for exercise 2. Obviously in future formatting would also need to be fixed but with the examples given and since Jenkins doesn't enforce it here I think it would be unfair to make you fix it all.

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/main.cpp
> +    for (auto& itr : mapWordCounter){
```suggestion
    for (auto &itr : mapWordCounter){
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/main.cpp
> +{
```suggestion
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/main.cpp
> +int main(int argc, char** argv)
```suggestion
int main(int argc, char** argv) {
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/processLine.h
> +void accountForWord(std::map<std::string,int>&, const std::string&);
```suggestion
void accountForWord(std::map<std::string,int> &, const std::string &);
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/processLine.h
> +void processLine(const std::string&, const std::vector<char>&, std::map<std::string,int>&);
```suggestion
void processLine(const std::string &, const std::vector<char> &, std::map<std::string,int> &);

```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/processLine.cpp
> +}
```suggestion
}

```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/main.cpp
> +    std::cout << "File to be processed: "  << argv[1] << "\n";
```suggestion
       std::cout << "File to be processed: "  << argv[1] << "\n";
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/main.cpp
> +
```suggestion
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/main.cpp
> +    std::vector<std::pair<std::string,int>> vecWordCounter;
```suggestion
    std::vector<std::pair<std::string, int>> vecWordCounter;
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/main.cpp
> +    std::map<std::string,int> mapWordCounter;
```suggestion
    std::map<std::string, int> mapWordCounter;
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/processLine.cpp
> +void accountForWord(std::map<std::string,int>& inputMap, const std::string& inputWord){
```suggestion
void accountForWord(std::map<std::string, int> &inputMap, const std::string &inputWord){
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/processLine.cpp
> +    inputMap.insert(std::pair<std::string,int>(inputWord,1));
```suggestion
        inputMap.insert(std::pair<std::string, int>(inputWord, 1));
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/processLine.cpp
> +void processLine(const std::string& lineInput, const std::vector<char>& delimiters, std::map<std::string,int>& inputMap){
```suggestion
void processLine(const std::string &lineInput, const std::vector<char> &delimiters, std::map<std::string,int> &inputMap){
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/main.cpp
> +    for_each(vecWordCounter.cbegin(), vecWordCounter.cend(), [&outputFile](auto& itr) {outputFile << itr.first << "\t" << itr.second << "\n";});
Would this also work here? using this seems more modern, and inline with LLVM coding standards.
```suggestion
    for (auto &vecCounted : vecWordCounter) {
        outputFile << vecCounted[0] << "\t" || vecCounted[1] << "\n";
    }
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/main.cpp
> +    std::vector<char> delimiters = {'\'','\"','.',',','?','!','(',')',':',' ','-','}'};
```suggestion
    std::vector<char> delimiters = {'\'', '\"', '.', ',', '?', '!',
                                    '(',  ')',  ':', ' ', '-', '}'};
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/main.cpp
> +    sort(vecWordCounter.begin(), vecWordCounter.end(), [](auto& a, auto& b){ return a.second > b.second;});
We *should* define we are using the STL when intending to otherwise it has to guess what you meant and not only may pick a different function than intended but may take longer at compilation time (Negligible on it's own but if it happens 10,000 times in a code base it builds up etc etc) https://en.cppreference.com/w/cpp/language/adl
```suggestion
    std::sort(vecWordCounter.begin(), vecWordCounter.end(),
         [](auto &a, auto &b) { return a.second > b.second; });
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex01_basics/src/main.cpp
> +       throw std::runtime_error("Atleast one argument (filename) should be passed. USAGE: ./a.out inputFileName");
```suggestion
      throw std::runtime_error("Atleast one argument (filename) should be "
                               "passed. USAGE: ./a.out inputFileName");
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex02_oo_basics/src/Circle.cpp
> +Circle::Circle(const std::string& inputType, const unsigned int& input_N_Sides, const double& inputRadius)
Suggestion:
```
Circle::Circle(const std::string &inputType, const unsigned int &input_N_Sides,
               const double &inputRadius)
    : Shape::Shape(inputType, input_N_Sides), radius{inputRadius} {}
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex02_oo_basics/src/Rectangle.cpp
> +Rectangle::Rectangle(const std::string& inputType, const unsigned int& input_N_Sides, const double& inputSide1, const double& inputSide2)
Another formatting suggestion:
```
Rectangle::Rectangle(const std::string &inputType,
                     const unsigned int &input_N_Sides,
                     const double &inputSide1, const double &inputSide2)
    : Shape::Shape(inputType, input_N_Sides), side1{inputSide1},
      side2{inputSide2} {}

Rectangle::Rectangle(const std::string &inputType,
                     const unsigned int &input_N_Sides, const double &inputSide)
    : Shape::Shape(inputType, input_N_Sides), side1{inputSide},
      side2{inputSide} {}
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex02_oo_basics/src/Shape.cpp
> +Shape::Shape(const std::string& inputType, const unsigned int& input_N_Sides)
Formatting suggestion:
```
Shape::Shape(const std::string &inputType, const unsigned int &input_N_Sides)
    : type{inputType}, nSides{input_N_Sides} {}

void Shape::calculateInfo() {
  calculatePerimeter();
  calculateArea();
}

void Shape::printInfo() const {
  std::cout << "Type: " << type << "\t"
            << "nSides: " << nSides << "\t"
            << "Perimeter: " << perimeter << "\t"
            << "Area: " << area << "\n";
}
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex02_oo_basics/src/ShapeSorter.cpp
> +    sort(vecShape.begin(), vecShape.end(), [] (auto& itrShape1, auto& itrShape2) {return itrShape1->getArea() > itrShape2->getArea();} );
I mentioned using std:: namespace explicitly in exercise 1, the same thing here with every sort in this .cpp file.

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex02_oo_basics/src/ShapeSorter.cpp
> +    for_each(vecShape.begin(), vecShape.end(), [] (const auto& itrShape) { itrShape->printInfo(); });
Again we should use range based for loops where possible.

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex02_oo_basics/src/Shape.h
> +class Shape{
Each class should have it's own .h file unless it's an internal class used only inside of a class.

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex02_oo_basics/src/Shape.h
> +
Re-format suggestion (Obviously splitting these classes into different files):
```
#include <cmath>
#include <iostream>

class Shape {

protected:
  std::string type;
  unsigned int nSides;
  double perimeter;
  double area;

public:
  Shape(const std::string &, const unsigned int &);

  virtual void calculatePerimeter() {}
  virtual void calculateArea() {}
  void calculateInfo();

  std::string getType() const { return type; }
  unsigned int get_N_Sides() const { return nSides; }
  double getPerimeter() const { return perimeter; }
  double getArea() const { return area; }

  bool isSameType(const std::string &inputType) const {
    return type == inputType;
  }
  bool hasEqual_N_Sides(const unsigned int &input_N_Sides) const {
    return nSides == input_N_Sides;
  }

  void printInfo() const;
};

class Rectangle : public Shape {

private:
  double side1, side2;

public:
  Rectangle(const std::string &, const unsigned int &, const double &,
            const double &);
  Rectangle(const std::string &, const unsigned int &, const double &);
  void calculatePerimeter() override { perimeter = 2 * (side1 + side2); }
  void calculateArea() override { area = side1 * side2; }
};

class Circle : public Shape {

private:
  double radius;

public:
  Circle(const std::string &, const unsigned int &, const double &);
  void calculatePerimeter() override { perimeter = 2.0 * M_PI * radius; }
  void calculateArea() override { area = M_PI * radius * radius; }
};

class Triangle : public Shape {

private:
  double base, height;

public:
  Triangle(const std::string &inputType, const unsigned int &, const double &,
           const double &);
  void calculatePerimeter() override {
    perimeter = base + 2 * sqrt(height * height + (base * base) / 4);
  }
  void calculateArea() override { area = 0.5 * base * height; }
};
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex02_oo_basics/src/main.cpp
> +    for_each(vecShape.begin(), vecShape.end(), [](auto& itrShape){itrShape->calculateInfo();});
Just reiterating range base for loops, this line is long enough for clang-format to shorten it anyway so a range based for will be clearer here.

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex02_oo_basics/src/ShapeSorter.h
> +#include "Shape.h"
```
#include "Shape.h"
#include <algorithm>
#include <memory>
#include <vector>

class ShapeSorter {

public:
  ShapeSorter(){};
  void areaDescent(std::vector<std::unique_ptr<Shape>> &);
  void perimeterDescent(std::vector<std::unique_ptr<Shape>> &);
  void equal_N_Sides(const std::vector<std::unique_ptr<Shape>> &,
                     const unsigned int &);
  void sameType(const std::vector<std::unique_ptr<Shape>> &,
                const std::string &);
```

2021-02-15 16:05 UTC, Pasarus commented on exercises/srikanth_ravipati/ex02_oo_basics/src/Triangle.cpp
> +Triangle::Triangle(const std::string& inputType, const unsigned int& input_N_Sides, const double& inputBase, const double& inputHeight)
```
Triangle::Triangle(const std::string &inputType,
                   const unsigned int &input_N_Sides, const double &inputBase,
                   const double &inputHeight)
    : Shape::Shape(inputType, input_N_Sides), base{inputBase},
      height{inputHeight} {}
```

2021-03-04 09:35 UTC, srikanthravipati commented
Hi Sam, 

Thanks for taking time to review the PR and for all the suggestions.
 I have done changes following your suggestions. 
It was also good exercise for me to get used to the nice and clean formatting.

> This is for Exercise 1:
> I am curious as to why you separated the processLine.cpp/.h files out? would it have made more sense to leave it in the main.cpp/.h files, considering it's such a small program.

You are right that the program is very small. Still, processLine includes user defined logic/functions for a specific task, and I prefer to keep it independent. This should allow easier reusability and testing. Happy to hear your opinion on that.

2022-12-22 11:09 UTC, closed without merging